### ISSUE TITLE
Approval/Reject decision not going through

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/grants-round#247] opened 2022-08-05 13:00 UTC
**Overview**

Fetch the application status from contract instead of relying on the graph
For more context refer this:
https://discord.com/channels/562828676480237578/1011646812127502427/1011955061401845780

This task would involve a few things:
- ensuring we log errors where IPFS call fails in graph
- ensure projectsMetaPtr is saved so that the frontend can use that to make a call to the contract and fetch the latest approval/rejection state

**Comment by thelostone-mc** [comment] 2022-08-05 16:19
This is not a bug and instead an expected situation of the subgraph indexing !
Ideally it shouldn't be too long once the txn succeeds. 
@nfrgosselin could you give this another try and record how long it took after the txn succeeded to it being reflected on the UI

**Comment by shavinac** [comment] 2022-08-15 22:02
This is happening, with >30 minute delay on the subgraph indexing 😬 

Example: I created a round [0xbb7240d08e2ebbf54bda6e7fa8e14b4ccb6665e2](https://rmgitcoin.on.fleek.co/#/round/0xbb7240d08e2ebbf54bda6e7fa8e14b4ccb6665e2), applied to the round, and rejected the application. ([transaction on goerli etherscan here](https://goerli.etherscan.io/tx/0x2b46fc5a050d45d27e99535e2ce25f79438a34fce0845766551d9a186cf4f4d6))

The subgraph `GetGrantApplications` query returns:
```
{
  "data": {
    "roundProjects": [
      {
        "id": "0x3339000000000000000000000000000000000000000000000000000000000000-0xbb7240d08e2ebbf54bda6e7fa8e14b4ccb6665e2",
        "metaPtr": {
          "protocol": 1,
          "pointer": "bafkreigu7i6gt35kfcnso22x2xbh5skjni5wacikpgz3ne6u6hcxckizxu"
        },
        "status": "PENDING",
        "round": {
          "projectsMetaPtr": {
            "protocol": 1,
            "pointer": "bafkreigfvyxtsk5wuxpduxgsgonfuc25tqvtn77thvbhgzmn5woxlkwt6i"
          }
        }
      }
    ]
  }
}
```
Note the `status` is still `PENDING`, but the `projectsMetaPtr` is up-to-date as `bafkreigfvyxtsk5wuxpduxgsgonfuc25tqvtn77thvbhgzmn5woxlkwt6i`.

[Loading projectsMetaPtr from IPFS](https://gitcoin.mypinata.cloud/ipfs/bafkreigfvyxtsk5wuxpduxgsgonfuc25tqvtn77thvbhgzmn5woxlkwt6i) shows that the `status` is already `REJECTED` though
```
[
  {
    "id": "0x3339000000000000000000000000000000000000000000000000000000000000-0xbb7240d08e2ebbf54bda6e7fa8e14b4ccb6665e2",
    "status": "REJECTED",
    "payoutAddress": "0x5bd8C4Ec48cf3EFDD791B5BAb2d4869342605F98"
  }
]
```

**Comment by shavinac** [comment] 2022-08-16 18:57
Reaching out to graphprotocol team on Discord for ways to speed up indexing - see [message in graphprotocol discord](https://discord.com/channels/438038660412342282/791444347823980604/1009145314839642222) `#hosted-service` channel

discussion in `#round-manager` channel in ["bug subgraph not updating" thread](https://discord.com/channels/562828676480237578/1009122340317171712)

**Comment by thelostone-mc** [comment] 2022-08-22 15:19
Nudging graph team once more over at https://discord.com/channels/438038660412342282/791444347823980604/1011292412162871337

**Comment by thelostone-mc** [comment] 2022-08-24 11:18
Synced up with the team and this would need to be updated for the short term and long term solution!
See the reasoning here: 
https://discord.com/channels/562828676480237578/1011646812127502427/1011955061401845780

I'll be closing this issue after creating the 2 tickets and we can prioritize the short term to get this fixed

**Closed** 2022-08-26 14:22 UTC
Labels: bug

**Comment by nfrgosselin** [comment] 2022-09-03 15:28
Overall this definitely seems quicker, although I've noticed the user has to refresh the page to trigger the update. I'm going to accept this fix but would love for us to have a general chat about UX / turnaround times
