### ISSUE TITLE
Decrypt emails

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/grants-round#222] opened 2022-07-28 18:24 UTC
**User Story:**
As a RM engineer
I want to decrypt emails received in applications
So that round operators can see each project's email address

**Acceptance Criteria**
- RM displays decrypted application email on application detail page

**Product & Design Links:**

**Tech Details:**

**Open Questions:**

**Notes/Assumptions:**
- This includes writing test coverage for the functionality added in the ticket, if necessary

**Comment by thelostone-mc** [comment] 2022-08-03 22:27
This depends on #220

**Comment by thelostone-mc** [comment] 2022-08-10 10:34
Conversation tracked at : https://discord.com/channels/562828676480237578/1002279206706749470/1006871997176893442

**Comment by thelostone-mc** [comment] 2022-08-10 18:18
Moving this back to blocked as we are waiting for hub team to provide us with a schema!

- need to check with lit team if it's okay to upload symmertric key on ipfs

**Comment by thelostone-mc** [comment] 2022-08-22 06:06
@nfrgosselin There is one callout here that as number of encrypted fields increase -> the number of signature will increase which is not a nice experience

**Comment by thelostone-mc** [comment] 2022-08-25 08:22
Figured out how to conditionally import the module to let us get past this error

**Comment by nfrgosselin** [comment] 2022-09-03 15:08
@thelostone-mc is there an action that the round operator needs to take? I can't see the email on my application:



![Image](https://user-images.githubusercontent.com/15041635/188276687-cd7a735f-e18f-4645-89e7-f3cbe990a7bc.png)

**Comment by thelostone-mc** [comment] 2022-09-06 10:32
Could you share more details on this ?

- Round 
- did you get any prompt from metamask 
- When you submitted the application -> was the email ID provided ? 
- Could you try refreshing once ?

**Comment by thelostone-mc** [comment] 2022-09-06 12:16
I was able to reproduce this. We should talk to grant-hub team on this. It looks like they changed the encryption rule

![Image](https://user-images.githubusercontent.com/5358146/188632661-2886a0e7-2042-4816-b903-22ba3ab04680.png)

**Comment by thelostone-mc** [comment] 2022-09-07 11:28
paired on this with @gravityblast#9625 
found the issue and andrea is getting out a fix :raised_hands:

@nfrgosselin  this should be good to test once they roll out the fix onto staging

**Closed** 2022-09-08 11:04 UTC

**Comment by nfrgosselin** [comment] 2022-09-11 15:51
LGTM
